### ISSUE TITLE
Autowire in AWS Lambda Java runtime

### ISSUE THREAD

**Issue by NE0Nsunset** [lihaoyi/autowire#82]
I'm attempting to setup a lambda function in Amazon AWS on the Java 8 runtime that would handle all the frontend requests through an autowired lambda function at /api. To create a fat jar for AWS, I'm using sbt-assembly. 

When I execute the lambda function, I'm getting a match error at the line:

```scala
AutowireServer.routes(autowire.Core
      .Request(path.split("/"),
               upickle.default.read[Map[String, String]](bodyJson)))
```

> Request(WrappedArray("lambda, api, SimpleApi, twoPlusN"),Map(n -> 1)) (of class autowire.Core$Request): scala.MatchError
scala.MatchError: Request(WrappedArray("lambda, api, SimpleApi, twoPlusN"),Map(n -> 1)) (of class autowire.Core$Request)
at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:255)
at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:253)
at lambda.Main$$anonfun$1.applyOrElse(Main.scala:97)
at lambda.Main$$anonfun$1.applyOrElse(Main.scala:97)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
at lambda.Main$.autowireApiController(Main.scala:99)
at lambda.Main$.autowireApiHandler(Main.scala:70)
at lambda.Main.autowireApiHandler(Main.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)

And AutowireServer looks like this:

```scala
object AutowireServer extends autowire.Server[String,upickle.default.Reader,upickle.default.Writer] {
    def write[Result: upickle.default.Writer](r: Result) =
      upickle.default.write(r)

    def read[Result: upickle.default.Reader](p: String) =
      upickle.default.read[Result](p)

    val routes = AutowireServer.route[SimpleApi](SimpleApiImpl)
  }
```

I can run the compiled jar locally on a 1.8 runtime (I've gone so far as using the same runtime AWS is supposedly using for their Java lambdas, java-1.8.0-openjdk) and it runs fine. The autowire.Macros#routeMacro creates the PartialFunction fine and I get the expected result. I've compared the arguments given to autowire.Core.Request in AWS and locally and they are exactly the same. 

I know this isn't necessarily an issue with Autowire, as it works locally in traditional environments, but I'm wondering if anyone has any insight as to why the macro seemingly fails to create a partial function in AWS.

**Comment by NE0Nsunset** [comment]
My problem was path had quotes around it that I didn't notice from parsing AWS' event body and they were included in the arguments.
